#theme: jekyll-theme-cayman



title: AzadRasul.io
email: azad977@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
#This is Remote Sensing and GIS website.
baseurl: "AzadRasul" # the subpath of your site, e.g. /blog
collections:
  my_collection:
    output: true
    permalink: /:collection/:name
#url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Azad77Rasul
github_username:  Azad77

# Build settings
theme: minima
plugins:
  - jekyll-feed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


